apiVersion: v1
kind: Secret
metadata:
  name: face-recognition-secrets
type: Opaque
stringData:
{{- if .Values.envFile }}
  {{- $cleanContent := replace "\r" "" .Values.envFile }}
  {{- range $line := splitList "\n" $cleanContent }}
    {{- if and $line (not (hasPrefix "#" $line)) (contains "=" $line) }}
      {{- $parts := splitn "=" 2 $line }}
  {{ $parts._0 | trim }}: {{ $parts._1 | trim | quote }}
    {{- end }}
  {{- end }}
{{- end }}